name: Daily Telegram Report

on:
  schedule:
    - cron: '0 6 * * *'   # Chạy lúc 11h40 trưa giờ Việt Nam (4h40 UTC)
  workflow_dispatch:      # Cho phép chạy thủ công từ GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev
          pip install -r requirements.txt

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          python ER_HN02_Ca_1.py